name: Docker Image CI

on:
  push:
    branches: [ main ]
    
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.DOCKER_REPOSITORY_NAME }}
  TAG: v0.0.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        docker build -t $DOCKER_USER/$REPO_NAME:$TAG .
    - name: docker push
      run: |
        docker push $DOCKER_USER/$REPO_NAME:$TAG
